### ISSUE TITLE
Feature request: Allow customizing the number of columns

### ISSUE THREAD

**Issue by 64kramsystem** [accessd/the-last-sunday#1]
I find more intuitive to have 10-column rows rather than 15; part of this is that life is typically associated with decades (20s, 30s...).

I think it'd be useful to allow the user specify the number of columns (or change it to 10, from the current 20).

**Comment by accessd** [comment]
Now you can specify the number of columns by:

`$HOME/terminal_sunday.sh 1985-06-08 Joe 10`

the main thing is that 80 is divisible without a remainder by this number of columns :)

**Comment by 64kramsystem** [comment]
Thank you!
